# tomcat端口号
server:
  address: 0.0.0.0
  port: 8080


spring:
  # 生产环境
  profiles:
    active: test
  # 热部署
  devtools:
    restart:
      enabled: true

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tust.bilibili.mapper



